import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { WodProvider } from "./context/WodContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-nunito">
        <Header />
        <WodProvider>{children}</WodProvider>
      </body>
    </html>
  );
}
